### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [nats-io/terraform-provider-jetstream#10]
Hi All, 

My name is Chris and I am part of the partner alliances team here at HashiCrop.  I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the master branch at git commit [e596ba5](https://github.com/nats-io/terraform-provider-jetstream/commit/e596ba5ba9ce08778526f6fdd677051dafb55937) 

- [x] The files name `jetstream.go` and `jetstream_test.go`should be changed to `provider.go` and `provider_test.go`

- [x] The resource file naming convention is as follows, `resource_providername_resource_name.go` which means the file `resource_consumer.go` should be named `resource_jetstream_consumer.go` and its corresponding acceptance test should be named `resource_jetstream_consumer_test.go`, this should be follows across all resource and data source files.

- [ ] One main addition is the GNUmakefile which is standard across all Terraform providers, feel free to copy the [GitHub provider makefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=jestream

- [ ] Along with the makefile, there are a few more scripts that are needed for testing and building the provider integration. You’ll need to add [gofmtcheck.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/gofmtcheck.sh), [changelog-links.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/changelog-links.sh) and [gogetcookie.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/gogetcookie.sh) to a scripts/ directory. 

- [ ] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in each TF providers. 

- [ ] All of our Terraform providers use a [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/) within each repo, can you replace your Apache license with this [LICENSE](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/LICENSE) file to this repository?

- [x] The website documentation should be written and put in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html). Each resource and data source will have its own page with arguments, attributes, usage examples and another useful documentation for  these are all written in markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example.  The Terraform website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy the website locally follow the steps outlined in the README.
	- Once you've synced the current submodules there are 3 more steps required for adding you provider
	- Add the jetstream provider as a submodule to the terraform-website/ directory with: `git submodule add -b master https://github.com/nats-io/terraform-provider-jetstream ext/providers/jetstream`
	- Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run: `ln -s ../../../../ext/providers/jetstream/website/docs jetstream`
	- And then change to the working directory to "terraform-website/content/source/layouts/" to run: `ln -s ../../../ext/providers/jetstream/website/jetstream.erb`
	- After those additions, you can then run the "make website" target to spin up the website using Docker desktop. 

Let me know if you have any question,
Best,
Chris

**Comment by ripienaar** [comment]
@cgriggs01 thanks for this, we'll certainly onboard some of these suggestions - though not all as we decided not to go into the current style provider registry but wait for the new one (we're a beta tester), the new one with its new release process etc would mean we can skip for examle the `vendor` suggestion etc.

**Comment by cgriggs01** [comment]
Hi @ripienaar,

Thanks for letting me know. For the time being, would you want me to add this to our [community providers page](https://www.terraform.io/docs/providers/type/community-index.html)?

Let me know any I'll get you added.

**Comment by ripienaar** [comment]
Oh, that would be nice thanks @cgriggs01 just `NATS JetStream` linked to this would be excellent thank you
