### ISSUE TITLE
Adding new filter_subjects to a nats consumer causes "Error: consumer subject filters cannot overlap (10138)"

### ISSUE THREAD

**Issue by IvanWillsBI** [nats-io/terraform-provider-jetstream#113]
### What version were you using?

Terraform version: v1.8.2
nats-server: v2.10.14

### What environment was the server running in?

ubuntu

### Is this defect reproducible?

Change:
`
resource "jetstream_consumer" "email_po_create" {
  durable_name   = "email_po_create"
  stream_id      = jetstream_stream.email.id
  filter_subjects = [
    "email.po_create.dlq",
    "email.po_create.non_uk_order",
  ]
  ack_policy     = "explicit"
  ack_wait       = 300
  replay_policy  = "instant"
  deliver_all    = true
}
`
to:
`
resource "jetstream_consumer" "email_po_create" {
  durable_name   = "email_po_create"
  stream_id      = jetstream_stream.email.id
  filter_subjects = [
    "email.po_create.dlq",
    "email.po_create.non_uk_order",
    "email.po_create.new_customer",
 ]
  ack_policy     = "explicit"
  ack_wait       = 300
  replay_policy  = "instant"
  deliver_all    = true
}
`

### Given the capability you are leveraging, describe your expectation?

successful terraform apply step

### Given the expectation, what is the defect you are observing?

Unsuccessful terraform apply step
overlapping filter subjects reported

**Comment by hansolo228-dev** [comment]
@IvanWillsBI  
Have you managed to solve this problem?

**Comment by ripienaar** [comment]
This should be fixed in next major release once NATS Server 2.11 is out.

**Comment by hansolo228-dev** [comment]
@ripienaar 
is this a problem on nats side?

**Comment by ripienaar** [comment]
There was a bug in the provider.
