### ISSUE TITLE
Provider TLS configuration

### ISSUE THREAD

**Issue by rickardgranberg** [nats-io/terraform-provider-jetstream#23]
I'm looking at using the Jetstream Provider as part of our Terraform NATS deployment.
I've configured NATS to use TLS, with certificates generated by cert-manager in our K8s cluster which is working well, but because of this I run into a problem using the Jetstream Provider since the Root CA in our cluster is not known/trusted.

As a workaround, I could install the Root CA cert on the machines I run Terraform on, but I'd much rather have this a provider argument, something like:

```
provider "jetstream" {
  servers     = "connect.ngs.global:4222"
  credentials = "/home/you/ngs_stream_admin.creds"
  tls {
    ca_file = "/some/file"
    ca_file_data = "<cert-string>"
    cert_file = ...
   ...
  }
}
```

Thoughts?

**Comment by ripienaar** [comment]
essentially you want to add ca_file_data?

**Comment by rickardgranberg** [comment]
> essentially you want to add ca_file_data?

Yes, that would solve my problem

**Comment by ripienaar** [comment]
I would esssentially have to make a temp file with that data in anyway - or even worse make a tlsc.  Probably can be done I guess :)

**Comment by ripienaar** [comment]
I have some work due here to cach up with our GA so will look at it soon

**Comment by rickardgranberg** [comment]
Sounds good!

**Comment by rickardgranberg** [comment]
Any news on this issue?

**Comment by ripienaar** [comment]
Unfortunately have not had time to revisit this

**Comment by rickardgranberg** [comment]
I decided to try my hand at implementing the missing feature, please let me know if you have any comments or questions!
