### ISSUE TITLE
provider checks the connectivity to nats server during initialisation of provider

### ISSUE THREAD

**Issue by sblgo** [nats-io/terraform-provider-jetstream#26]
in my configuration I combine to provider docker and nats-jetstream.
With the docker provider, the script creates the nats jetstream server. Because of the jetstream provider checks the connectivity to the jetstream server during provider setup, my terraform script allways fails.

```
terraform {
  required_providers {
   jetstream = {
      source = "nats-io/jetstream"
    }

    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

provider "docker" {
}

provider "jetstream" {
  servers     = "192.168.1.90:4222"   // <-- this fails
}

resource "docker_network" "nats_network" {
  name = "nats_nw"
}

resource "docker_container" "nats_docker" {
  image = "nats:latest"
  name  = "nats"
  ports {
    internal = 4222
    external = 4222
  }
  networks_advanced {
      name = docker_network.nats_network.name
  }
  command = ["-js"]
}

resource "jetstream_stream" "ORDERS" {
  name     = "ORDERS"
  subjects = ["ORDERS.*"]
  storage  = "file"
  max_age  = 60 * 60 * 24 * 365
}

```

**Comment by ripienaar** [comment]
Hmm, yeah that's annoying, however I don't think TF gives a good way to do late bindings of connections - I cant see how to get access to the provider config in the resources.  Will take a closer look

**Comment by ripienaar** [comment]
I think #27 probably fixes this, we'll hopefully do releases this week

**Comment by sblgo** [comment]
you can also use golang Once from the golang package sync.
