### ISSUE TITLE
Context deadine exceeded

### ISSUE THREAD

**Issue by thanhdinh-manabie** [nats-io/terraform-provider-jetstream#46]
I got this error when running terraform apply with this configuration
```
terraform {
  required_providers {
    jetstream = {
      source = "nats-io/jetstream"
      version = "0.0.28"
    }
  }
}

provider "jetstream" {
  servers     = "localhost:4222"
}

resource "jetstream_stream" "ORDERS" {
  name     = "ORDERS"
  subjects = ["ORDERS.*"]
}

resource "jetstream_consumer" "ORDERS_NEW" {
  stream_id      = jetstream_stream.ORDERS.id
  durable_name   = "NEW"
  deliver_all    = true
  filter_subject = "ORDERS.received"
}
```
Error logs:
![image](https://user-images.githubusercontent.com/81950926/150660099-c06783f6-5d85-42d6-b207-ada4a42761a3.png)

I have nats server running on local already. How could I resolve this problem? Thank you in advance.

**Comment by thanhdinh-manabie** [comment]
This solved. I forgot to run jetstream service when running nats server

**Comment by bobbybhaskar** [comment]
Hi @thanhdinh-manabie 
Where did you install "jetstream service" in windows or Linux. If you installed in windows, can please share the installation steps for windows jetstream

Thanks,
Bobby
