### ISSUE TITLE
Enhance CI - Use GH Actions to build and publish terraform provider

### ISSUE THREAD

**Issue by mikenabhan** [nats-io/terraform-provider-jetstream#61]
Hello, 

If you provide me with the current process that you are using to build and publish the provider, I am happy to recreate this process in GH actions to release and increment version according to SemVer on every merge to the main branch.

**Comment by ripienaar** [comment]
Hello

the process is essentially just to run tests followed by goreleaser. I review the draft release and once GH gets a final release the terraform registry auto updates

**Comment by mikenabhan** [comment]
I will submit a PR to do this in GH actions for review if it is a welcome change.

**Comment by ripienaar** [comment]
Yeah would be good for sure to see GH used to do the goreleaser work
