### ISSUE TITLE
How to add source stream from different JS Domain

### ISSUE THREAD

**Issue by jasase** [nats-io/terraform-provider-jetstream#72]
We want to add a source stream link to a stream in a different js domain like described in this documentation. 
https://docs.nats.io/running-a-nats-service/configuration/leafnodes/jetstream_leafnodes#see-also

I didn't seen any way to configure this with this provider. Can you please help us?

**Comment by ripienaar** [comment]
When creating the mirror/source you should add `external` and then set the prefixes there.  The clients have some helpers to do this but in Terraform you'll have to do what the helpers does basically.

https://github.com/nats-io/terraform-provider-jetstream/blob/01883129bc1f583975c0c3bba2a7230cc8667036/jetstream/resource_jetstream_stream.go#L15-L59

**Comment by alexsladkov** [comment]
It would be great if you could provide an example in terraform syntax on how to define a jetstream_stream resource with a source stream from a different jetstream domain.  I can not figure out how to define the other stream's domain.  "api" and "deliver" fields of the "external" define the subjects, not the domain name.  
I am looking at the terraform documentation here: https://registry.terraform.io/providers/nats-io/jetstream/latest/docs/resources/jetstream_stream
Thanks a lot for your help!

**Comment by ripienaar** [comment]
The easiest way to see what to fill in there is to add the stream cross domains using the nats cli and then doing `nats s info STREAM --json` you'll see how the subjects are mapped.

"domain" in the cli is syntax sugar that generates these api/external etc stuff based on patterns, terraform doesnt really lend itself to that kind of syntactic sugar so you need to know the underlying values which above method will give you

**Comment by alexsladkov** [comment]
Thanks a lot, @ripienaar! I got one step further and can create a jetstream_stream, which sources a stream from another domain. 
```
resource "jetstream_stream" "NewResourceName" {
  name     = "NewStreamName"
  source { 
    name = "ForegnStreamName" 
    external {
      api = "$JS.ForeignStreamDomain.API"
    }
  }
  subjects = [ "YourSubject" ]
  storage  = "file"
}
```
This issue can be closed, I suppose.
But I have another problem now: I want to source multiple streams (all of them coming from different domains - which is not a problem any more).  Is it possible to have multiple sources in  jetstream_stream definition (CLI allows it)?  Documentation says: `source` (optional) List of streams to source.  But it does not accept list definition syntax [{}, {}].   Am I missing something?

**Comment by alexsladkov** [comment]
PERFECT!  Yes, it works!  Thank you very much, @ripienaar!
I also compared the configuration of streams (stream info --json) created by terraform and by CLI, with multiple sources with different domains -- the only difference is "allow_direct" default value: false by CLI, true by terraform.  Terraform aims for better performance, I guess :)

**Comment by ripienaar** [comment]
Hmm probsbly an oversight here. Or perhaps it’s been a while since we released and defaults changed.

**Comment by ripienaar** [comment]
This and CLI use the same library underneath, will see what the story is
