### ISSUE TITLE
Using provider for private clusters

### ISSUE THREAD

**Issue by csuriano23** [nats-io/terraform-provider-jetstream#77]
Hi there,
is there a way to use the provider for a cluster on private AWS VPC?

Thank you

**Comment by ripienaar** [comment]
I cant think of any reason why it wont work? Are you wondering how to install it without access to terraform plugin store?

**Comment by csuriano23** [comment]
I've tried creating a provider like this:

```terraform
provider "jetstream" {
  servers     = "my.private.domain:4222"
  user          = ...
  password = ...
}
```

But I get error on applying since DNS can't solve `my.private.domain`, something like:

`Error: dial tcp: lookup my.private.domain on 192.168.1.1:53: no such host`
Since it non-public, my.private.domain can only be solved inside AWS Route53.

Am I missing something?

**Comment by ripienaar** [comment]
This suggest where you are running terraform isn’t part of the target network. You need to be able to connect there at a basic level sometning like “telnet my.priv.domain 4222” should work. 

This doesn’t seem to be related to terraform.
