### ISSUE TITLE
Release cadence 

### ISSUE THREAD

**Issue by alxyng** [nats-io/terraform-provider-jetstream#78]
Hey guys, how are we all?

We're keen to use this provider to declare some streams as part of our infrastructure. What's stopping us is that those spicy new `discard` and `discard_new_per_subject` options aren't in a release yet. This provider looks like a very fresh but very useful project and I was wondering if you could share some thoughts on when you'll be releasing new versions in the future.

We're big fans of Jetstream, nice work guys!

Thanks from the folks at @LavaGames

**Comment by ripienaar** [comment]
Hey, thanks for the kind words.

I'd typically do a release around the time the next major server (2.10) comes along, but I think for this it's fine to do earlier.  I'll look later this week if i can get a new one out.

**Comment by alxyng** [comment]
Hey, thanks for the speedy response. We'll keep our eye out for the next release, nice one!

**Comment by ripienaar** [comment]
I did a release https://github.com/nats-io/terraform-provider-jetstream/releases/tag/v0.0.35 let me know how it goes.  Looks like we would soon need to upgrade to terraforms new plugin sdk :(
