### ISSUE TITLE
Add support for multi subject filter consumers

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/terraform-provider-jetstream#98]
### What motivated this proposal?

With the release of NATS 2.10, support for multiple subject filter consumers is a value-added feature.

### What is the proposed change?

Update the `jetstream_consumer` resource to allow for multiple subject filters.

### Who benefits from this change?

This benefits anyone on 2.10 who plans to use multiple subject consumers.

**Comment by ripienaar** [comment]
Should be fixed in https://github.com/nats-io/terraform-provider-jetstream/pull/99
